import { WidgetDefinition } from "./widget-types";

export const WIDGET_DEFINITIONS: WidgetDefinition[] = [
  {
    key: "WIDGET_DIGITAL_CLOCK",
    title: "Jam Digital & Status Operasional",
    category: "UTILITY",
    description: "Menampilkan jam digital, tanggal, dan status buka/tutup outlet.",
    defaultColSpan: 1,
    allowedColSpans: [1, 2],
    icon: "Clock",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_REVENUE_TODAY",
    title: "Omzet & Transaksi Hari Ini",
    category: "SUMMARY",
    description: "Ringkasan total pendapatan hari ini, jumlah transaksi, dan estimasi laba bersih.",
    defaultColSpan: 1,
    allowedColSpans: [1, 2],
    icon: "DollarSign",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_DAILY_TARGET",
    title: "Target Pencapaian Harian",
    category: "SUMMARY",
    description: "Progress bar target omzet harian dengan persentase pencapaian real-time.",
    defaultColSpan: 1,
    allowedColSpans: [1, 2],
    icon: "Target",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_QUICK_ACTIONS",
    title: "Menu Pintas Cepat",
    category: "UTILITY",
    description: "Akses cepat untuk membuka kasir POS, menambah produk, atau melihat laporan.",
    defaultColSpan: 1,
    allowedColSpans: [1, 2, 4],
    icon: "Zap",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_CHART_7DAYS",
    title: "Grafik Tren Penjualan 7 Hari",
    category: "CHART",
    description: "Visualisasi grafik pendapatan operasional selama 7 hari terakhir.",
    defaultColSpan: 2,
    allowedColSpans: [2, 3, 4],
    icon: "TrendingUp",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_RECENT_TRANSACTIONS",
    title: "Transaksi Terkini",
    category: "SUMMARY",
    description: "Daftar transaksi kasir terbaru yang baru saja diselesaikan.",
    defaultColSpan: 2,
    allowedColSpans: [2, 3, 4],
    icon: "Receipt",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_LOW_STOCK_ALERT",
    title: "Peringatan Stok Menipis",
    category: "SUMMARY",
    description: "Daftar item produk yang jumlah stoknya berada di bawah batas minimum.",
    defaultColSpan: 2,
    allowedColSpans: [1, 2, 3, 4],
    icon: "AlertTriangle",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_VERTICAL_STATUS",
    title: "Status Operasional (Meja/Kursi/Rak)",
    category: "VERTICAL",
    description: "Status meja aktif (Cafe), antrean kapster (Barber), atau status rak cucian (Laundry).",
    defaultColSpan: 2,
    allowedColSpans: [2, 3, 4],
    icon: "Store",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_PEAK_HOURS_MINI",
    title: "Grafik Jam Ramai Hari Ini",
    category: "CHART",
    description: "Ringkasan grafik jam operasional tersibuk hari ini.",
    defaultColSpan: 2,
    allowedColSpans: [2, 4],
    icon: "Flame",
    requiredPlugin: null,
  },
];
