import { WidgetDefinition } from "./widget-types";

export const WIDGET_DEFINITIONS: WidgetDefinition[] = [
  {
    key: "WIDGET_DIGITAL_CLOCK",
    title: "Jam Digital & Status Operasional Toko",
    category: "UTILITY",
    description: "Menampilkan jam digital live presisi, tanggal masehi, dan status buka/tutup cabang toko.",
    defaultColSpan: 1,
    allowedColSpans: [1, 2],
    icon: "Clock",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_REVENUE_TODAY",
    title: "Omzet & Transaksi Hari Ini",
    category: "SUMMARY",
    description: "Kartu ringkasan total pendapatan kasir hari ini, jumlah transaksi, dan estimasi laba bersih.",
    defaultColSpan: 1,
    allowedColSpans: [1, 2],
    icon: "DollarSign",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_DAILY_TARGET",
    title: "Target Pencapaian Omzet Harian",
    category: "SUMMARY",
    description: "Progress bar target omzet harian/bulanan dengan persentase pencapaian real-time.",
    defaultColSpan: 1,
    allowedColSpans: [1, 2],
    icon: "Target",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_QUICK_ACTIONS",
    title: "Shortcut POS & Aksi Kilat",
    category: "UTILITY",
    description: "Tombol pintas untuk langsung buka kasir POS, tambah produk baru, atau cetak laporan.",
    defaultColSpan: 1,
    allowedColSpans: [1, 2, 4],
    icon: "Zap",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_CHART_7DAYS",
    title: "Grafik Tren Penjualan 7 Hari",
    category: "CHART",
    description: "Visualisasi grafik batang / area interaktif pendapatan toko selama 7 hari terakhir.",
    defaultColSpan: 2,
    allowedColSpans: [2, 3, 4],
    icon: "TrendingUp",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_RECENT_TRANSACTIONS",
    title: "Live Feed Transaksi Terakhir",
    category: "SUMMARY",
    description: "Daftar struk transaksi belanja terbaru yang baru saja diselesaikan oleh kasir.",
    defaultColSpan: 2,
    allowedColSpans: [2, 3, 4],
    icon: "Receipt",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_LOW_STOCK_ALERT",
    title: "Peringatan Stok Barang Menipis",
    category: "SUMMARY",
    description: "Daftar produk inventori yang jumlah stoknya berada di bawah batas minimum.",
    defaultColSpan: 2,
    allowedColSpans: [1, 2, 3, 4],
    icon: "AlertTriangle",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_VERTICAL_STATUS",
    title: "Live Operasional Vertikal (Meja/Kursi/Rak)",
    category: "VERTICAL",
    description: "Status meja aktif (Cafe), antrean kapster (Barber), atau status rak cucian (Laundry).",
    defaultColSpan: 2,
    allowedColSpans: [2, 3, 4],
    icon: "Store",
    requiredPlugin: null,
  },
  {
    key: "WIDGET_PEAK_HOURS_MINI",
    title: "Mini Heatmap Jam Ramai Hari Ini",
    category: "CHART",
    description: "Grafik mini aktivitas jam operasional tersibuk toko hari ini.",
    defaultColSpan: 2,
    allowedColSpans: [2, 4],
    icon: "Flame",
    requiredPlugin: null,
  },
];
