import { FeatureEntitlement } from "./types";

export const DEFAULT_FEATURE_ENTITLEMENTS: FeatureEntitlement[] = [
  // ── 1. KATEGORI LAPORAN & ANALITIK ──
  {
    key: "REPORT_SALES_BASIC",
    name: "Ringkasan Penjualan & Transaksi Harian",
    category: "REPORTS",
    description: "Melihat total omzet kotor, jumlah transaksi harian, dan metode pembayaran kasir.",
    allowedTiers: ["basic", "starter", "pro", "enterprise"],
    requiredPlugin: null,
    isPublicPreview: true,
  },
  {
    key: "REPORT_PROFIT_LOSS",
    name: "Analisis Margin Laba Bersih & HPP",
    category: "REPORTS",
    description: "Kalkulasi laba bersih riil, estimasi modal pokok penjualan (HPP), dan margin keuntungan produk.",
    allowedTiers: ["pro", "enterprise"],
    requiredPlugin: null,
    isPublicPreview: true,
  },
  {
    key: "REPORT_EXPORT_EXCEL",
    name: "Export Laporan Lengkap ke Excel & PDF",
    category: "REPORTS",
    description: "Unduh seluruh pembukuan transaksi dalam format CSV/Excel dan dokumen PDF siap audit.",
    allowedTiers: ["pro", "enterprise"],
    requiredPlugin: null,
    isPublicPreview: true,
  },
  {
    key: "REPORT_HOURLY_PEAK",
    name: "Analitik Grafik Jam Sibuk Transaksi",
    category: "REPORTS",
    description: "Visualisasi jam ramai operasional untuk mengoptimalkan jumlah staf kasir yang bertugas.",
    allowedTiers: ["pro", "enterprise"],
    requiredPlugin: null,
    isPublicPreview: true,
  },
  {
    key: "REPORT_MULTI_OUTLET",
    name: "Laporan Konsolidasi & Komparasi Antar-Cabang",
    category: "REPORTS",
    description: "Membandingkan omzet, laba kotor, dan performa seluruh outlet cabang dalam 1 layar.",
    allowedTiers: ["pro", "enterprise"],
    requiredPlugin: null,
    isPublicPreview: true,
  },

  // ── 2. KATEGORI KASIR POS & OPERASIONAL ──
  {
    key: "POS_CORE_CHECKOUT",
    name: "Kasir POS Cepat Multi-Metode Bayar",
    category: "CORE_POS",
    description: "Antarmuka kasir kilat dengan pembayaran QRIS, Tunai, Kartu Debit, dan Transfer.",
    allowedTiers: ["basic", "starter", "pro", "enterprise"],
    requiredPlugin: null,
    isPublicPreview: true,
  },
  {
    key: "POS_CUSTOM_DISCOUNT",
    name: "Input Diskon Manual & Voucher Kasir",
    category: "CORE_POS",
    description: "Fitur potongan harga persentase atau nominal langsung saat transaksi di kasir.",
    allowedTiers: ["pro", "enterprise"],
    requiredPlugin: null,
    isPublicPreview: true,
  },
  {
    key: "POS_SPLIT_BILL",
    name: "Split Bill / Pisah Tagihan Pembayaran",
    category: "CORE_POS",
    description: "Memungkinkan pelanggan dalam 1 pesanan/meja membayar secara terpisah.",
    allowedTiers: ["pro", "enterprise"],
    requiredPlugin: null,
    isPublicPreview: true,
  },

  // ── 3. KATEGORI INVENTORI & STAFF ──
  {
    key: "INVENTORY_LOW_STOCK_ALERT",
    name: "Peringatan Stok Menipis & Minimum Threshold",
    category: "INVENTORY",
    description: "Notifikasi otomatis saat jumlah persediaan barang di gudang/outlet berada di bawah batas minimum.",
    allowedTiers: ["basic", "starter", "pro", "enterprise"],
    requiredPlugin: null,
    isPublicPreview: true,
  },
  {
    key: "STAFF_ROLE_ISOLATION",
    name: "Hak Akses Admin Cabang & Kasir Terisolasi",
    category: "STAFF",
    description: "Membatasi akun kasir agar hanya bisa melihat data outlet tempat mereka ditugaskan.",
    allowedTiers: ["pro", "enterprise"],
    requiredPlugin: null,
    isPublicPreview: true,
  },
  {
    key: "STAFF_SHIFT_AUDIT",
    name: "Buka/Tutup Shift Kasir & Rekonsiliasi Kas",
    category: "STAFF",
    description: "Pencatatan kas modal awal, pengeluaran kasir, dan selisih kas fisik saat pergantian shift.",
    allowedTiers: ["basic", "starter", "pro", "enterprise"],
    requiredPlugin: null,
    isPublicPreview: true,
  },

  // ── 4. KATEGORI VERTIKAL: CAFE & F&B ──
  {
    key: "CAFE_TABLE_MANAGEMENT",
    name: "Denah Meja & Live Floor Management",
    category: "CAFE",
    description: "Kelola status meja, tata letak, kapasitas kursi, dan pesanan meja aktif secara visual.",
    allowedTiers: ["basic", "starter", "pro", "enterprise"],
    requiredPlugin: "cafe",
    isPublicPreview: true,
  },
  {
    key: "CAFE_KITCHEN_ORDER_TICKET",
    name: "Tiket Pesanan Otomatis ke Dapur & Bar (KOT)",
    category: "CAFE",
    description: "Cetak slip pesanan khusus divisi dapur dan divisi bar secara terpisah tanpa jeda.",
    allowedTiers: ["basic", "starter", "pro", "enterprise"],
    requiredPlugin: "cafe",
    isPublicPreview: true,
  },
  {
    key: "CAFE_REPORT_ANALYTICS",
    name: "Analitik Okupansi Meja & Rasio Food vs Drink",
    category: "CAFE",
    description: "Laporan waktu rata-rata nongkrong meja, varian rasa terlaris, dan rasio makanan/minuman.",
    allowedTiers: ["pro", "enterprise"],
    requiredPlugin: "cafe",
    isPublicPreview: true,
  },

  // ── 5. KATEGORI VERTIKAL: BARBERSHOP & SALON ──
  {
    key: "BARBER_CHAIR_QUEUE",
    name: "Live Chair Board & Antrean Kursi Potong",
    category: "BARBER",
    description: "Manajemen stasiun kursi pangkas aktif dan estimasi giliran antrean pelanggan.",
    allowedTiers: ["basic", "starter", "pro", "enterprise"],
    requiredPlugin: "barbershop",
    isPublicPreview: true,
  },
  {
    key: "BARBER_COMMISSION_SYSTEM",
    name: "Kalkulator Komisi & Tip Kapster Otomatis",
    category: "BARBER",
    description: "Penugasan kapster per item jasa dan perhitungan bagi hasil komisi otomatis tanpa rekap manual.",
    allowedTiers: ["basic", "starter", "pro", "enterprise"],
    requiredPlugin: "barbershop",
    isPublicPreview: true,
  },
  {
    key: "BARBER_REPORT_ANALYTICS",
    name: "Analitik Kinerja Kapster & Penjualan Pomade",
    category: "BARBER",
    description: "Laporan leaderboard omzet per kapster dan rasio cross-selling produk styling takeaway.",
    allowedTiers: ["pro", "enterprise"],
    requiredPlugin: "barbershop",
    isPublicPreview: true,
  },

  // ── 6. KATEGORI VERTIKAL: LAUNDRY SERVICE ──
  {
    key: "LAUNDRY_DECIMAL_WEIGHT",
    name: "Kalkulator Timbangan Desimal Kg Kilat",
    category: "LAUNDRY",
    description: "Perhitungan biaya akurat berdasarkan berat timbangan desimal (misal 3.45 Kg) dan harga per Kg.",
    allowedTiers: ["basic", "starter", "pro", "enterprise"],
    requiredPlugin: "laundry",
    isPublicPreview: true,
  },
  {
    key: "LAUNDRY_RACK_MANAGEMENT",
    name: "Penomoran Slot Rak Penyimpanan Cucian",
    category: "LAUNDRY",
    description: "Pelacakan posisi rak penyimpanan (misal Rak B-04) untuk memudahkan pengambilan cucian jadi.",
    allowedTiers: ["basic", "starter", "pro", "enterprise"],
    requiredPlugin: "laundry",
    isPublicPreview: true,
  },
  {
    key: "LAUNDRY_REPORT_ANALYTICS",
    name: "Analitik SLA Cucian & Parfum Terfavorit",
    category: "LAUNDRY",
    description: "Laporan persentase ketepatan waktu selesai, volume Kg harian, dan distribusi aroma parfum.",
    allowedTiers: ["pro", "enterprise"],
    requiredPlugin: "laundry",
    isPublicPreview: true,
  },

  // ── 7. KATEGORI VERTIKAL: RETAIL & MART ──
  {
    key: "RETAIL_BARCODE_SCAN",
    name: "Auto-Focus Barcode Scanner & Touch Numpad",
    category: "RETAIL",
    description: "Input cepat dengan scanner barcode fisik dan tombol kuantitas touchscreen jumbo.",
    allowedTiers: ["basic", "starter", "pro", "enterprise"],
    requiredPlugin: "retail",
    isPublicPreview: true,
  },
  {
    key: "RETAIL_MULTI_UNIT",
    name: "Multi-Satuan Barang (Dus / Lusin / Pcs)",
    category: "RETAIL",
    description: "Beli stok dalam satuan karton/dus besar dan jual eceran per pcs dengan konversi otomatis.",
    allowedTiers: ["pro", "enterprise"],
    requiredPlugin: "retail",
    isPublicPreview: true,
  },
  {
    key: "RETAIL_REPORT_ANALYTICS",
    name: "Analisis Pareto Fast-Moving vs Dead-Stock",
    category: "RETAIL",
    description: "Laporan perputaran inventori SKU cepat laku vs barang mengendap di rak lebih dari 30 hari.",
    allowedTiers: ["pro", "enterprise"],
    requiredPlugin: "retail",
    isPublicPreview: true,
  },
];
